### ISSUE TITLE
find_element_by is now depreciated.

### ISSUE THREAD

**Issue by brandon-toner** [egefeyzioglu/mymedia-download#1]
I received the following error while running the script. Authentication was successful, but nothing was downloaded.

`Authenticated. Collecting video URLs... Traceback (most recent call last):
  File "/Users/<username>/Downloads/./mymedia-downloader.py", line 82, in <module>
    titles.append(driver.find_element_by_css_selector("h2.chakra-heading").text)
AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'
`

**Comment by brandon-toner** [comment]
Related: https://stackoverflow.com/questions/72773206/selenium-python-attributeerror-webdriver-object-has-no-attribute-find-el

**Comment by egefeyzioglu** [comment]
Thanks @brandon-toner !
