### ISSUE TITLE
Doesn't work on M2 Macbook

### ISSUE THREAD

**Issue by 1Dbcj** [egefeyzioglu/mymedia-download#2]
Hi there, I'm having an issue where it can't install the selenium version on a M2 Macbook, and with the new versions, multiple lines/arguments don't work. Is there any way to update this to newer versions of selenium? 

does this program still work with MyMedia?

**Comment by egefeyzioglu** [comment]
Yeah it looks like there were some breaking changes with selenium. Will fix when I get the chance (feel free to fix yourself and open a merge request if you'd like)

**Comment by egefeyzioglu** [comment]
Sorry for the delay, just fixed this. Please lmk if you're still having issues with the tool
